services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3369:3369/tcp
      - 3329:3329/udp
    stop_grace_period: 2m
