services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 5900:5900
      - 5901:5901/tcp
      - 5902:5902/udp
    stop_grace_period: 2m
